-- Mini Scrum DB Schema (Oracle)
-- Schema: AT9

-- 팀원
CREATE TABLE AT9.MINI_SCRUM_MEMBERS (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  role VARCHAR2(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 스프린트 (주 단위)
CREATE TABLE AT9.MINI_SCRUM_SPRINTS (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  goal VARCHAR2(1000),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 업무
CREATE TABLE AT9.MINI_SCRUM_TASKS (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sprint_id NUMBER REFERENCES AT9.MINI_SCRUM_SPRINTS(id),
  title VARCHAR2(200) NOT NULL,
  description VARCHAR2(2000),
  assignee_id NUMBER REFERENCES AT9.MINI_SCRUM_MEMBERS(id),
  status VARCHAR2(20) DEFAULT 'todo',
  priority VARCHAR2(10) DEFAULT 'medium',
  due_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 주간 리뷰
CREATE TABLE AT9.MINI_SCRUM_REVIEWS (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sprint_id NUMBER REFERENCES AT9.MINI_SCRUM_SPRINTS(id),
  incomplete_reason VARCHAR2(2000),
  blockers VARCHAR2(2000),
  next_plan VARCHAR2(2000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 팀 규칙
CREATE TABLE AT9.MINI_SCRUM_RULES (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  content VARCHAR2(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 회고 (KPT)
CREATE TABLE AT9.MINI_SCRUM_RETROSPECTIVES (
  id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sprint_id NUMBER REFERENCES AT9.MINI_SCRUM_SPRINTS(id),
  member_id NUMBER REFERENCES AT9.MINI_SCRUM_MEMBERS(id),
  keep_items VARCHAR2(2000),
  problem_items VARCHAR2(2000),
  try_items VARCHAR2(2000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
